export const URL_KEYS = {
    ORGANIZATION_ID: 'organizationId',
    SPECIALIST_ID: 'specialist_id',
    SPECIALIST_CATEGORY_ID: 'specialist_category_id',
    SEARCH: 'search',
    GROUP_ID: 'groupId',
    SEARCH_FILTER_TYPE: 'filterType',
    CATEGORY_ID: 'categoryId',
    SHOW_FILTER:'showFilter',
    STEP: 'step',
    SETTINGS_TYPE: 'settings_type',
    OFFERING_GROUP_ID: 'offering_group_id',
    OFFERING_PARAM_ID: 'offering_param_id',
    SELLER:'seller',
    STREAM_SLUG: 'stream_slug',
    JOB_ID: 'job_id',
    FILTER_TYPE: 'filter_type',
    VERIFICATION_STEP: 'verification_step',
    PARAMS:'params',
    COST_MIN: 'cost_min',
    COST_MAX: 'cost_max',
    PAGE: 'page',
    ORDER_BY:'order_by',
    PARENT_ID: 'parent_id',
    DATE: 'date',
    TIME: 'time',
    TEXT: 'text',
    NEXT: 'next',
    TAB: 'tab',
    STATUS: 'status'
}

export const URL_VALUES = {
    GROUPS: 'groups',
    TAPE: 'tape',
    OFFERINGS: 'offerings',
    ORGANIZATION: 'organization',
    PEOPLE: 'people',
    LIVE: 'live',
    PHONE_VERIFY: 'phone_verify',
    CHANGE_PHONE: 'change_phone',
    PERSONAL_INFO: 'personal_info',
    SECURITY: 'security',
    CHAT: 'chat',
    NOTIFICATION: 'notification',
    PAYMENT: 'payment',
    LANG: 'lang',
    STREAM: 'stream',
    PROFILE: 'profile',
    CONTACT: 'contact',
    COUPON: 'coupon'
}

export const PARAM_KEYS = {
    RESPONSIBLE: 'responsible',
    GROUP: 'group',
    SEARCH: 'search',
    SPECIALIST: 'specialist',
    SPEC_CAT: 'spec_cat'
}