export const ru = {
    'header.image_editor_title': 'DWED Фото редактор',
    'header.toggle_fullscreen': 'Включить полноэкранный режим',
    'header.close': 'Закрыть',
    'header.close_modal': 'Закрыть окно',
    'toolbar.download': 'Загрузть',
    'toolbar.save': 'Сохранить',
    'toolbar.apply': 'Применить',
    'toolbar.saveAsNewImage': 'Сохранить как новое изображение',
    'toolbar.cancel': 'Отменить',
    'toolbar.go_back': 'Назад',
    'toolbar.adjust': 'Регулировать ',
    'toolbar.effects': 'Эффекты',
    'toolbar.filters': 'Фильтеры',
    'toolbar.orientation': 'Орентация',
    'toolbar.crop': 'Обрезать ',
    'toolbar.resize': 'Изменить размер',
    'toolbar.watermark': 'Водяной знак ',
    'toolbar.focus_point': 'Точка фокусировки ',
    'toolbar.shapes': 'Фигуры',
    'toolbar.image': 'Изображение ',
    'toolbar.text': 'Текст',
    'adjust.brightness': 'Яркость ',
    'adjust.contrast': 'Контраст',
    'adjust.exposure': 'Экспозиция',
    'adjust.saturation': 'Насыщенность ',
    'orientation.rotate_l': 'Повернуть налево',
    'orientation.rotate_r': 'Повернуть вправо ',
    'orientation.flip_h': 'Отразить по горизонтали ',
    'orientation.flip_v': 'Отразить по вертикали',
    'pre_resize.title': 'Вы хотите уменьшить разрешение перед редактированием изображения?',
    'pre_resize.keep_original_resolution': 'Сохранить исходное разрешение',
    'pre_resize.resize_n_continue': 'Изменить размер и продолжить ',
    'footer.reset': 'Сбросить',
    'footer.undo': 'Undo',
    'footer.redo': 'Redo',
    'spinner.label': 'В процессе...',
    'warning.too_big_resolution': 'Разрешение изображения слишком велико для Интернета. Это может вызвать проблемы с производительностью редактора изображений. ',
    'common.x': 'x',
    'common.y': 'y',
    'common.width': 'ширина',
    'common.height': 'высота',
    'common.custom': 'пользовательский',
    'common.original': 'оригинал',
    'common.square': 'квадрат',
    'common.opacity': 'Прозрачность',
    'common.apply_watermark': 'Применить водяной знак',
    'common.url': 'URL',
    'common.upload': 'Загрузить ',
    'common.gallery': 'Галерея',
    'common.text': 'Текст',
}

export const imageEditorConfig = {
    tools: ['crop', 'rotate', 'resize', 'adjust', 'effects', 'filters'],
    language: 'ru',
    isLowQualityPreview: false,
    reduceBeforeEdit: {
        mode: 'manual',
        widthLimit: 2000,
        heightLimit: 2000
    },
    translations: {
        ru
    },
    theme: {
        colors: {
            primaryBg: '#ffffff',
            primaryBgHover: '#f2f2f2',
            secondaryBg: '#F8FAFB',
            secondaryBgHover: '#DFE7ED',
            secondaryBgOpacity: 'rgba(255,255,255, 0.75)',
            text: '#8F9BB3',
            textHover: '#1a2329',
            textMute: '#aaa',
            textWarn: '#f7931e',
            accent: '#D5D8DC',
            button: {
                primary: '#1DA1F2',
                secondary: '#ffffff',
                border: 'transparent',
                hover: '#66C5FF',
                active: '#1DA1F2'
            },
            border: '#DFE7ED',
            borderLight: '#e1e1e1',
            disabledBg: 'rgba(255, 0, 0, 0.1)',
        }
    }
}